### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by honzajavorek**
Missing full license text complicates using this package in enterprise environments.

A new version, 2.3.4, should be released once this gets merged.

### CODE REVIEW

**Comment by opichals** [comment]
@isaacs Hi Isaac! What is your position on this? Would you consider merging this?

**Comment by isaacs** [comment]
The license was already in the package on npm (and has been since initial release), I just had neglected to add it to git.

```
$ npm pack minipass
npm notice
npm notice 📦  minipass@2.3.4
npm notice === Tarball Contents ===
npm notice 777B  package.json
npm notice 9.3kB index.js
npm notice 756B  LICENSE
npm notice 3.5kB README.md
npm notice === Tarball Details ===
npm notice name:          minipass
npm notice version:       2.3.4
npm notice filename:      minipass-2.3.4.tgz
npm notice package size:  5.2 kB
npm notice unpacked size: 14.4 kB
npm notice shasum:        4768d7605ed6194d6d576169b9e12ef71e9d9957
npm notice integrity:     sha512-mlouk1OHlaUE8[...]M6aC+Tn6lUZ5w==
npm notice total files:   4
```

**Comment by opichals** [comment]
@isaacs Thanks for adding the license.

Not sure what mean about the npm previously containing the LICENSE file. See below:

```
$ npm view minipass@2.3.3 dist.tarball | xargs curl -s | tar t
package/package.json
package/index.js
package/README.md
```

**Comment by isaacs** [comment]
Huh.  Well that's weird, there was already a LICENSE file sitting there in the repo on my machine.  Maybe I got halfway through fixing this at some point after the most recent release, and just didn't finish it?

**Pull request closed without merging**
