### PR TITLE
fix event emitter type mismatches

### PR DESCRIPTION
**Pull request by paulsmithkc**
Fixes https://github.com/isaacs/minipass/issues/49

Adds methods overloads to the `Minipass` class, which match the signatures required by the `EventEmitter` base class. 

See [node:events](https://nodejs.org/docs/latest-v18.x/api/events.html)

### CODE REVIEW

**Comment by paulsmithkc** [comment]
@isaacs Can we get some eyes on this patch?

**Comment by isaacs** [comment]
Is the issue just that `symbol` isn't allowed?

Ie, couldn't this work instead?

```diff
diff --git a/index.d.ts b/index.d.ts
index 86384b0..6437bad 100644
--- a/index.d.ts
+++ b/index.d.ts
@@ -69,7 +69,7 @@ export namespace Minipass {
     : ObjectModeOptions
 
   interface EventArguments {
-    [k: string]: unknown[]
+    [k: string | symbol]: unknown[]
   }
   /**
    * The listing of events that a Minipass class can emit.

```

**Comment by isaacs** [comment]
The reason I'm suggesting that is that it's a quite nice type safety feature to have the arguments to event handlers be set as `unknown` by default for undeclared events, so that they have to be type checked before use, rather than `any`, which tells TS to ignore them entirely and just lets you do anything.

**Comment by paulsmithkc** [comment]
@isaacs My proposed changes do preserve type safety for known types. However the overloads are needed and must match exactly with the types in Node's EventEmitter class.

**Comment by isaacs** [comment]
They don't preserve type safety for undeclared events, though.

What error are you seeing with the latest Minipass publish?  I'm using this now in rimraf, glob, and the next-gen version of tap, without any problems.

**Pull request closed without merging**
